//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AssetSplit = newAssetSplitTable("public", "asset_split", "")

type assetSplitTable struct {
	postgres.Table

	//Columns
	AssetSplitID postgres.ColumnInteger
	Symbol       postgres.ColumnString
	Ratio        postgres.ColumnInteger
	Date         postgres.ColumnTimestampz
	CreatedAt    postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type AssetSplitTable struct {
	assetSplitTable

	EXCLUDED assetSplitTable
}

// AS creates new AssetSplitTable with assigned alias
func (a AssetSplitTable) AS(alias string) *AssetSplitTable {
	return newAssetSplitTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AssetSplitTable with assigned schema name
func (a AssetSplitTable) FromSchema(schemaName string) *AssetSplitTable {
	return newAssetSplitTable(schemaName, a.TableName(), a.Alias())
}

func newAssetSplitTable(schemaName, tableName, alias string) *AssetSplitTable {
	return &AssetSplitTable{
		assetSplitTable: newAssetSplitTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newAssetSplitTableImpl("", "excluded", ""),
	}
}

func newAssetSplitTableImpl(schemaName, tableName, alias string) assetSplitTable {
	var (
		AssetSplitIDColumn = postgres.IntegerColumn("asset_split_id")
		SymbolColumn       = postgres.StringColumn("symbol")
		RatioColumn        = postgres.IntegerColumn("ratio")
		DateColumn         = postgres.TimestampzColumn("date")
		CreatedAtColumn    = postgres.TimestampzColumn("created_at")
		allColumns         = postgres.ColumnList{AssetSplitIDColumn, SymbolColumn, RatioColumn, DateColumn, CreatedAtColumn}
		mutableColumns     = postgres.ColumnList{SymbolColumn, RatioColumn, DateColumn, CreatedAtColumn}
	)

	return assetSplitTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		AssetSplitID: AssetSplitIDColumn,
		Symbol:       SymbolColumn,
		Ratio:        RatioColumn,
		Date:         DateColumn,
		CreatedAt:    CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
