//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PlaidItem = newPlaidItemTable("public", "plaid_item", "")

type plaidItemTable struct {
	postgres.Table

	//Columns
	ItemID      postgres.ColumnString
	PlaidItemID postgres.ColumnString
	CreatedAt   postgres.ColumnTimestampz
	AccessToken postgres.ColumnString
	UserID      postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PlaidItemTable struct {
	plaidItemTable

	EXCLUDED plaidItemTable
}

// AS creates new PlaidItemTable with assigned alias
func (a PlaidItemTable) AS(alias string) *PlaidItemTable {
	return newPlaidItemTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PlaidItemTable with assigned schema name
func (a PlaidItemTable) FromSchema(schemaName string) *PlaidItemTable {
	return newPlaidItemTable(schemaName, a.TableName(), a.Alias())
}

func newPlaidItemTable(schemaName, tableName, alias string) *PlaidItemTable {
	return &PlaidItemTable{
		plaidItemTable: newPlaidItemTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newPlaidItemTableImpl("", "excluded", ""),
	}
}

func newPlaidItemTableImpl(schemaName, tableName, alias string) plaidItemTable {
	var (
		ItemIDColumn      = postgres.StringColumn("item_id")
		PlaidItemIDColumn = postgres.StringColumn("plaid_item_id")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		AccessTokenColumn = postgres.StringColumn("access_token")
		UserIDColumn      = postgres.StringColumn("user_id")
		allColumns        = postgres.ColumnList{ItemIDColumn, PlaidItemIDColumn, CreatedAtColumn, AccessTokenColumn, UserIDColumn}
		mutableColumns    = postgres.ColumnList{PlaidItemIDColumn, CreatedAtColumn, AccessTokenColumn, UserIDColumn}
	)

	return plaidItemTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ItemID:      ItemIDColumn,
		PlaidItemID: PlaidItemIDColumn,
		CreatedAt:   CreatedAtColumn,
		AccessToken: AccessTokenColumn,
		UserID:      UserIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
