//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Transfer = newTransferTable("public", "transfer", "")

type transferTable struct {
	postgres.Table

	//Columns
	ActivityID   postgres.ColumnInteger
	Amount       postgres.ColumnFloat
	ActivityType postgres.ColumnString
	Date         postgres.ColumnDate
	CreatedAt    postgres.ColumnTimestampz
	ModifiedAt   postgres.ColumnTimestampz
	Custodian    postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type TransferTable struct {
	transferTable

	EXCLUDED transferTable
}

// AS creates new TransferTable with assigned alias
func (a TransferTable) AS(alias string) *TransferTable {
	return newTransferTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TransferTable with assigned schema name
func (a TransferTable) FromSchema(schemaName string) *TransferTable {
	return newTransferTable(schemaName, a.TableName(), a.Alias())
}

func newTransferTable(schemaName, tableName, alias string) *TransferTable {
	return &TransferTable{
		transferTable: newTransferTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newTransferTableImpl("", "excluded", ""),
	}
}

func newTransferTableImpl(schemaName, tableName, alias string) transferTable {
	var (
		ActivityIDColumn   = postgres.IntegerColumn("activity_id")
		AmountColumn       = postgres.FloatColumn("amount")
		ActivityTypeColumn = postgres.StringColumn("activity_type")
		DateColumn         = postgres.DateColumn("date")
		CreatedAtColumn    = postgres.TimestampzColumn("created_at")
		ModifiedAtColumn   = postgres.TimestampzColumn("modified_at")
		CustodianColumn    = postgres.StringColumn("custodian")
		allColumns         = postgres.ColumnList{ActivityIDColumn, AmountColumn, ActivityTypeColumn, DateColumn, CreatedAtColumn, ModifiedAtColumn, CustodianColumn}
		mutableColumns     = postgres.ColumnList{AmountColumn, ActivityTypeColumn, DateColumn, CreatedAtColumn, ModifiedAtColumn, CustodianColumn}
	)

	return transferTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ActivityID:   ActivityIDColumn,
		Amount:       AmountColumn,
		ActivityType: ActivityTypeColumn,
		Date:         DateColumn,
		CreatedAt:    CreatedAtColumn,
		ModifiedAt:   ModifiedAtColumn,
		Custodian:    CustodianColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
