version: '3.7'
services:
    postgres:
        image: postgres:14-alpine
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./migrations/0000_schema_version.sql:/docker-entrypoint-initdb.d/0000_schema_version.sql