//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type AppliedAssetSplit struct {
	AppliedAssetSplitID int32 `sql:"primary_key"`
	AssetSplitID        int32
	OpenLotID           int32
	AppliedAt           time.Time
}
