//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"

	"github.com/shopspring/decimal"
)

type AssetMetric struct {
	AssetMetricID                           int32 `sql:"primary_key"`
	Symbol                                  string
	FullName                                string
	Price                                   decimal.Decimal
	PriceUpdatedAt                          time.Time
	EarningsPerShareAnnualTrailing          decimal.Decimal
	EarningsPerShareAnnualTrailingUpdatedAt time.Time
	DividendYieldAnnualTrailing             decimal.Decimal
	DividendYieldAnnualTrailingUpdatedAt    time.Time
	PeRatioTrailing                         decimal.Decimal
	BookValue                               decimal.Decimal
	PriceToBookRatio                        decimal.Decimal
	SharesOutstanding                       decimal.Decimal
	MarketCap                               decimal.Decimal
}
