//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type AssetSplit struct {
	AssetSplitID int32 `sql:"primary_key"`
	Symbol       string
	Ratio        int32
	Date         time.Time
	CreatedAt    *time.Time
}
