//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type CashType string

const (
	CashType_Withdrawal CashType = "WITHDRAWAL"
	CashType_Deposit    CashType = "DEPOSIT"
)

func (e *CashType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "WITHDRAWAL":
		*e = CashType_Withdrawal
	case "DEPOSIT":
		*e = CashType_Deposit
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for CashType enum")
	}

	return nil
}

func (e CashType) String() string {
	return string(e)
}
