//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type BankActivityType string

const (
	BankActivityType_Withdrawal BankActivityType = "WITHDRAWAL"
	BankActivityType_Deposit    BankActivityType = "DEPOSIT"
)

func (e *BankActivityType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "WITHDRAWAL":
		*e = BankActivityType_Withdrawal
	case "DEPOSIT":
		*e = BankActivityType_Deposit
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for BankActivityType enum")
	}

	return nil
}

func (e BankActivityType) String() string {
	return string(e)
}
