//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type CustodianType string

const (
	CustodianType_Robinhood CustodianType = "ROBINHOOD"
	CustodianType_Tda       CustodianType = "TDA"
)

func (e *CustodianType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "ROBINHOOD":
		*e = CustodianType_Robinhood
	case "TDA":
		*e = CustodianType_Tda
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for CustodianType enum")
	}

	return nil
}

func (e CustodianType) String() string {
	return string(e)
}
