//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"

	"github.com/shopspring/decimal"
)

type Dividend struct {
	TradeID    int32 `sql:"primary_key"`
	Amount     decimal.Decimal
	Symbol     string
	Date       time.Time
	CreatedAt  *time.Time
	ModifiedAt *time.Time
}
