//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"

	"github.com/shopspring/decimal"
)

type Dividend struct {
	DividendID          int32 `sql:"primary_key"`
	Symbol              string
	Amount              decimal.Decimal
	Date                time.Time
	Custodian           CustodianType
	ReinvestmentTradeID *int32
	CreatedAt           *time.Time
}
