//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type PlaidItem struct {
	ItemID      uuid.UUID `sql:"primary_key"`
	PlaidItemID string
	CreatedAt   time.Time
	AccessToken string
	UserID      uuid.UUID
}
