//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type PlaidTradingAccountMetadata struct {
	PlaidAccountMetadataID uuid.UUID `sql:"primary_key"`
	TradingAccountID       uuid.UUID
	Mask                   *string
	ItemID                 uuid.UUID
	PlaidAccountID         string
}
