//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type PositionSourceType string

const (
	PositionSourceType_Manual PositionSourceType = "MANUAL"
	PositionSourceType_Plaid  PositionSourceType = "PLAID"
)

func (e *PositionSourceType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "MANUAL":
		*e = PositionSourceType_Manual
	case "PLAID":
		*e = PositionSourceType_Plaid
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for PositionSourceType enum")
	}

	return nil
}

func (e PositionSourceType) String() string {
	return string(e)
}
