//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type TradeActionType string

const (
	TradeActionType_Buy  TradeActionType = "BUY"
	TradeActionType_Sell TradeActionType = "SELL"
)

func (e *TradeActionType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "BUY":
		*e = TradeActionType_Buy
	case "SELL":
		*e = TradeActionType_Sell
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for TradeActionType enum")
	}

	return nil
}

func (e TradeActionType) String() string {
	return string(e)
}
