//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"

	"github.com/shopspring/decimal"
)

type Trade struct {
	TradeID     int32 `sql:"primary_key"`
	Symbol      string
	Action      TradeActionType
	Quantity    decimal.Decimal
	CostBasis   decimal.Decimal
	Date        time.Time
	Description *string
	CreatedAt   time.Time
	ModifiedAt  time.Time
	Custodian   CustodianType
}
