//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type TradingAccountDataSourceType string

const (
	TradingAccountDataSourceType_Trades    TradingAccountDataSourceType = "TRADES"
	TradingAccountDataSourceType_Positions TradingAccountDataSourceType = "POSITIONS"
)

func (e *TradingAccountDataSourceType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "TRADES":
		*e = TradingAccountDataSourceType_Trades
	case "POSITIONS":
		*e = TradingAccountDataSourceType_Positions
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for TradingAccountDataSourceType enum")
	}

	return nil
}

func (e TradingAccountDataSourceType) String() string {
	return string(e)
}
