//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/shopspring/decimal"
)

type VwHolding struct {
	Symbol   *string
	Quantity *decimal.Decimal
	NumLots  *int64
}
