//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"

	"github.com/shopspring/decimal"
)

type VwOpenLotPosition struct {
	OpenLotID       *int32
	TradeID         *int32
	Symbol          *string
	Quantity        *decimal.Decimal
	PurchaseDate    *time.Time
	CostBasis       *decimal.Decimal
	UnrealizedGains *decimal.Decimal
	GainsType       *string
	Price           *decimal.Decimal
	PriceUpdatedAt  *time.Time
}
