//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"

	"github.com/shopspring/decimal"
)

type VwOpenLot struct {
	OpenLotID    *int32
	Symbol       *string
	Quantity     *decimal.Decimal
	CostBasis    *decimal.Decimal
	PurchaseDate *time.Time
	HoldingType  *string
}
