//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/v2/postgres"
)

var LatestPrice = newLatestPriceTable("public", "latest_price", "")

type latestPriceTable struct {
	postgres.Table

	//Columns
	PriceID   postgres.ColumnInteger
	Symbol    postgres.ColumnString
	Price     postgres.ColumnFloat
	UpdatedAt postgres.ColumnTimestampz
	Date      postgres.ColumnDate

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type LatestPriceTable struct {
	latestPriceTable

	EXCLUDED latestPriceTable
}

// AS creates new LatestPriceTable with assigned alias
func (a LatestPriceTable) AS(alias string) *LatestPriceTable {
	return newLatestPriceTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LatestPriceTable with assigned schema name
func (a LatestPriceTable) FromSchema(schemaName string) *LatestPriceTable {
	return newLatestPriceTable(schemaName, a.TableName(), a.Alias())
}

func newLatestPriceTable(schemaName, tableName, alias string) *LatestPriceTable {
	return &LatestPriceTable{
		latestPriceTable: newLatestPriceTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newLatestPriceTableImpl("", "excluded", ""),
	}
}

func newLatestPriceTableImpl(schemaName, tableName, alias string) latestPriceTable {
	var (
		PriceIDColumn   = postgres.IntegerColumn("price_id")
		SymbolColumn    = postgres.StringColumn("symbol")
		PriceColumn     = postgres.FloatColumn("price")
		UpdatedAtColumn = postgres.TimestampzColumn("updated_at")
		DateColumn      = postgres.DateColumn("date")
		allColumns      = postgres.ColumnList{PriceIDColumn, SymbolColumn, PriceColumn, UpdatedAtColumn, DateColumn}
		mutableColumns  = postgres.ColumnList{PriceIDColumn, SymbolColumn, PriceColumn, UpdatedAtColumn, DateColumn}
	)

	return latestPriceTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		PriceID:   PriceIDColumn,
		Symbol:    SymbolColumn,
		Price:     PriceColumn,
		UpdatedAt: UpdatedAtColumn,
		Date:      DateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
