//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var AccountType = &struct {
	Individual postgres.StringExpression
	Ira        postgres.StringExpression
	RothIra    postgres.StringExpression
}{
	Individual: postgres.NewEnumValue("INDIVIDUAL"),
	Ira:        postgres.NewEnumValue("IRA"),
	RothIra:    postgres.NewEnumValue("ROTH_IRA"),
}
