//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var GainsType = &struct {
	ShortTerm postgres.StringExpression
	LongTerm  postgres.StringExpression
}{
	ShortTerm: postgres.NewEnumValue("SHORT_TERM"),
	LongTerm:  postgres.NewEnumValue("LONG_TERM"),
}
