//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var TradeActionType = &struct {
	Buy  postgres.StringExpression
	Sell postgres.StringExpression
}{
	Buy:  postgres.NewEnumValue("BUY"),
	Sell: postgres.NewEnumValue("SELL"),
}
