//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var TradeSourceType = &struct {
	Manual        postgres.StringExpression
	Plaid         postgres.StringExpression
	PlaidInferred postgres.StringExpression
}{
	Manual:        postgres.NewEnumValue("MANUAL"),
	Plaid:         postgres.NewEnumValue("PLAID"),
	PlaidInferred: postgres.NewEnumValue("PLAID_INFERRED"),
}
