//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var TradingAccountDataSourceType = &struct {
	Trades    postgres.StringExpression
	Positions postgres.StringExpression
}{
	Trades:    postgres.NewEnumValue("TRADES"),
	Positions: postgres.NewEnumValue("POSITIONS"),
}
